### PR TITLE
Chinese localization

### PR DESCRIPTION
**Pull request by NarekoMichigami810**
This idiot is back with his localization files, the translation is complete and you can merge directly.

### CODE REVIEW

**Comment by NarekoMichigami810** [comment]
uhhh

**Comment by BallOfEnergy1** [comment]
why is it from the space fork

**Comment by legendarydoge30** [comment]
>chinese localization
>is actually the entirety of ntm space

**Comment by NarekoMichigami810** [comment]
This idiot is using pr for the first time

**Pull request closed without merging**
