### PR TITLE
Add 1.12.2 Doors port

### PR DESCRIPTION
**Pull request by 0xaa55h**
# General Support for Drillgon's doors in 1.7.10  
This small update adds one thing every NTM player ever wanted: _1.12.2 Doors_   

_Feel free to comment my shit style code, I'm not very skilled in commiting to open-source projects which aren't mine_

### CODE REVIEW

**Comment by ghost** [comment]
shit

**Comment by 0xaa55h** [comment]
I'm now rewriting the item rendering for the doors into the undeprecated api

**Comment by 0xaa55h** [comment]
The PR should be ready now, if you have any notes let me know

**Comment by HbmMods** [comment]
Using the power of black magic fuckery, I have merged this automatically.

**Pull request merged**
