### PR TITLE
Compressing plastic

### PR DESCRIPTION
**Pull request by legendarydoge30**
Blocks for better storage management and fuel efficiency
Adds
- Block of PVC
- Block of Hard Plastic
- Block of Solid Fuel
- Block of Solid Fuel (Rocket Propellant)
- Block of Solid Fuel (Balefire)

### CODE REVIEW

**Comment by Ashen-sysadmin** [comment]
Again?

**Comment by legendarydoge30** [comment]
> Again?

Bobert said the bricks were sort of pointless so I removed them and kept the blocks that actually help with storage.
70k agreed with PRing it again.

**Comment by Ashen-sysadmin** [comment]
Sure, whatever.

**Comment by HbmMods** [comment]
image

i'm trying to reduce unnecessary use of block IDs, not add more blocks that don't have any actual functionality. if anything, compressed blocks should be one block with metadata

**Comment by legendarydoge30** [comment]
ok

**Pull request closed without merging**
