### PR TITLE
Calculator

### PR DESCRIPTION
**Pull request by MartinTheDragon**
Two-and-a-half-months-since-we-had-the-idea later, I finally finished the basic calculator.

image

### Features

- Basic operators + - * /
- The operator that is the cause of the delay: ^ (implementing this correctly took forever)
- Functions
    - sqrt
    - sin, cos, tan, asin, acos, atan
    - log, ln
    - ceil, floor, round
- Constants
    - PI
    - Euler's number
- Press Enter to put the result back into the input field, select it, and copy it to the clipboard.

Works with parentheses, of course.

`GUICalculator#evaluateExpression` can be statically used anywhere.

The calculator is client-side only. Use the 'N' key (Satisfactory inspired) to open the GUI. The key bind can be changed in the options menu.

Future features may include graphing, Minecraft unit conversion, ~~DOOM~~, and recipe calculation.

Also Bob, please do come back to the Discord server.

### CODE REVIEW

**Comment by HbmMods** [comment]
image

**Comment by Shibva** [comment]
Divide by zero, I QUACKIN DARE YOU

**Comment by MartinTheDragon** [comment]
> Divide by zero, I QUACKIN DARE YOU



Therefore dividing by 0 returns "Infinity".

**Comment by Shibva** [comment]
I meant a funny joke

If you were to input 1/0 specifically a singularity Would spawn

**Comment by MartinTheDragon** [comment]
Everybody gets that joke, do not worry.

**Pull request merged**
