### PR TITLE
Burst fire

### PR DESCRIPTION
**Pull request by 70000hp**
**Added**

Burst-fire firing mode to the gun system

- Self-explanatory, Change the firingDuration parameter to adjust how long does each individual shot takes, and roundsPerBurst to adjust how much shots per action
- Currently added as an alt-fire to the Josh (pretty much selective fire, prevents you from wasting 6 shots on one glyphid scout) and the UAC pistol (since it had that option in project brutality)

### CODE REVIEW

**Comment by HbmMods** [comment]
`burstDuration` can't be a simple field because that would mean every gun of the same type shares this value because items of the same type share instances. Either use NBT or one of the already existing timers.

**Comment by 70000hp** [comment]
> `burstDuration` can't be a simple field because that would mean every gun of the same type shares this value because items of the same type share instances. Either use NBT or one of the already existing timers.

Oh right, completly forgot, I'll add it to NBT

**Comment by 70000hp** [comment]
> `burstDuration` can't be a simple field because that would mean every gun of the same type shares this value because items of the same type share instances. Either use NBT or one of the already existing timers.

@HbmMods There we go, I converted it to use NBT

**Comment by HbmMods** [comment]
The UAC pistol has a burst size of 3, yet fires 6 times

**Comment by 70000hp** [comment]
Six? I've used it and it only fired 3 shots per burst

**Comment by 70000hp** [comment]
https://quickshare.samsungcloud.com/a0pAydJjZlP9

**Comment by HbmMods** [comment]
https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/16674258/bdbc6abb-fa15-4048-95c2-daebb5dd0d76

**Comment by 70000hp** [comment]
I just tested it in main ntm and it fired 3 shots like it was intended to
what

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/105080577/53f1ffa4-efea-4dfb-9382-4d6fa1c9277f

**Pull request merged**
