### PR TITLE
Make marking pipelines easier and quicker

### PR DESCRIPTION
**Pull request by MartinTheDragon**
Shift-right-clicking pipes with fluid identifiers will now change connected pipes within a maximum distance of 64 blocks.

You may want to add some info text in the fluid identifier's tooltip.
Or make the maximum distance configurable.

### CODE REVIEW

**Comment by MartinTheDragon** [comment]
Added info text

**Comment by HbmMods** [comment]
heythere

**Comment by MartinTheDragon** [comment]
Ye I just looked at the PR and you merged it right before my eyes

**Comment by HbmMods** [comment]
m a g i c

**Pull request merged**
