### PR TITLE
High Performance Radio-Alloy [New Material]

### PR DESCRIPTION
**Pull request by TheChosenIndividual**
Made from alloying Reactor Grade Plutonium and Uranium in a blast furnace, comes an amalgam like none other...

High Performance Radio-Alloy is a brand new material i coded into the game, it comes in ingot, powder, nugget, and billet forms, and can be formed into

-A mid tier RTG pellet
-A mid tier RBMK fuel
-A mid tier Self-Charging battery

it was designed for the purpose of making RGPU more useful, since it is not very effective as an RBMK fuel, but is okay for PWR (Which i do plan to add to its components in the future) with the purpose of turning all that reactor grade plutonium from the chicago pile, and turning it into fuel WITHOUT the need for an uranium enrichment plant, reliable, and cheap, good ol HPA, it also has a cool purple-violet color to it, and behaves with similar drops to Pu241 once recycled after a service cycle in an RBMK

(Synced to the latest commits on the master branch so HBM wont have to re-write a bunch of code, lol)

thanks for reading, and hope you consider it

-Chosen

### CODE REVIEW

**Comment by JameH2** [comment]
>be me
>8 year old sibling likes Minecraft, specifically NTM
>loves the 1.12 port because its on a newer and better version
>decide to join the discord
>immediately see 20 rbmk jokes and a russian discussing textures 
>join in
>see suggestions channel
>thiswillbegood.jpg
>immediately crack my knuckles, the pops practically sound like gunshots
>my keyboard starts to cry
>with the fury of my fingers, i start typing away my grand idea, sexually assaulting the keyboard at this point
>the police show up but can only watch in horror
>the enter key attempts suicide
>i start thinking how fucking cool this sounds
>my mind is currently heating to near cpu temps
>hmm yes, i wanna see “boltzium” maybe “digammium” oh! Even “sonicium” named after sonic my favorite!!
>come up with 2000 different isotopes
>each number makes me harder than ever
>hmm this is lacking something 
>call over brother
>hey why dont you take a crack?
>my pc practically screams, the police who have been watching this ordeal scream for the fbi
>my brother types away
>one police man glances at the screen, it blinds him for a bit
>i take a peek
>helo alater i wan a bom where it says “dont touch this..” it has the evil spirit of the earths core using pixarium-33382, an isotope found in grantite igneous sedimen
>itsbeautiful.jpg
>fbi bust down the door
>they drop their weapons, it’s practically a trance at this point 
>hmm, maybe we should finish up with a new mob?
>half of my cpu orders a union strike, the ceo of my computer hires a pmc to take care of it, the pmc, ceo, and cpu decide to quit in unison
>new mob: the ender god, it has 20 binjillion health and can NOT BE KILLED, IT MUST BE KILLED WITH THE DINNETRON-477337 AXE, MADE FROM GOING TO BED DURING BEDTIME
>wrap it up
>it doesnt look good, decide to feed it through chatgpt for formatting
>the openai servers go down
>company goes bankrupt 
>crater in where the datacenter once was
>eh whatever, hit “send”
>ethernet cable starts to cry, its also catching fire
>the discord datacenter has been compromised 
>message finally arrives with the force comparable of the asteroid that killed the dinosaurs 
>half of the discord datacenter wiped out
>alcaters screen starts to glow with a white halo, the german electrical grid has shut down, its acting on its own
>”what a good idea” he says, before being cast into the light of salvation

**Comment by TheChosenIndividual** [comment]
> > be me
> > 8 year old sibling likes Minecraft, specifically NTM
> > loves the 1.12 port because its on a newer and better version
> > decide to join the discord
> > immediately see 20 rbmk jokes and a russian discussing textures
> > join in
> > see suggestions channel
> > thiswillbegood.jpg
> > immediately crack my knuckles, the pops practically sound like gunshots
> > my keyboard starts to cry
> > with the fury of my fingers, i start typing away my grand idea, sexually assaulting the keyboard at this point
> > the police show up but can only watch in horror
> > the enter key attempts suicide
> > i start thinking how fucking cool this sounds
> > my mind is currently heating to near cpu temps
> > hmm yes, i wanna see “boltzium” maybe “digammium” oh! Even “sonicium” named after sonic my favorite!!
> > come up with 2000 different isotopes
> > each number makes me harder than ever
> > hmm this is lacking something
> > call over brother
> > hey why dont you take a crack?
> > my pc practically screams, the police who have been watching this ordeal scream for the fbi
> > my brother types away
> > one police man glances at the screen, it blinds him for a bit
> > i take a peek
> > helo alater i wan a bom where it says “dont touch this..” it has the evil spirit of the earths core using pixarium-33382, an isotope found in grantite igneous sedimen
> > itsbeautiful.jpg
> > fbi bust down the door
> > they drop their weapons, it’s practically a trance at this point
> > hmm, maybe we should finish up with a new mob?
> > half of my cpu orders a union strike, the ceo of my computer hires a pmc to take care of it, the pmc, ceo, and cpu decide to quit in unison
> > new mob: the ender god, it has 20 binjillion health and can NOT BE KILLED, IT MUST BE KILLED WITH THE DINNETRON-477337 AXE, MADE FROM GOING TO BED DURING BEDTIME
> > wrap it up
> > it doesnt look good, decide to feed it through chatgpt for formatting
> > the openai servers go down
> > company goes bankrupt
> > crater in where the datacenter once was
> > eh whatever, hit “send”
> > ethernet cable starts to cry, its also catching fire
> > the discord datacenter has been compromised
> > message finally arrives with the force comparable of the asteroid that killed the dinosaurs
> > half of the discord datacenter wiped out
> > alcaters screen starts to glow with a white halo, the german electrical grid has shut down, its acting on its own
> > ”what a good idea” he says, before being cast into the light of salvation

holy f*cking shit, well...uhhh...i...guess i can take it as a joke...?

**Comment by TheChosenIndividual** [comment]
I know this isnt the holy grail when it comes to ideas, but it also didnt just hatch from one day to another my man

**Comment by Troodontid** [comment]
This is effectively just MOX fuel made with unenriched uranium...

**Comment by 70000hp** [comment]
I really do not see the point of this PR at all
As PU said, it's just MOX fuel with extra steps

**Comment by HbmMods** [comment]
but why

**Comment by TheChosenIndividual** [comment]
Its...supposed to be cheaper, because MOX requires MEU, IE uranium enrichment, but HPA is only NU and RGP, also, Mox cant make self-charging batteries or RTG pellets can it?

**Comment by OlorinIV** [comment]
iirc there is an item in the mod called 'ingot of plutonium fuel', or lep in rbmk, which is rgp+u238, which is basically what this high-performance alloy is? It used to be one of the big reactor fuels, comes with this wonderful cycle that effectively burns away only u238, but no pwr version yet.

**Comment by HbmMods** [comment]
I don't understand, why do we need an ingot that is basically just MOX but with natural uranium? Why is the NU MOX better than regular MOX, despite having less U-235 content? Why is it suddenly a radioisotope? Why does the HPRA self-charger need a HPRA self-charger to craft? Why is there textures and localizations for single and double breeding rods (but no quad ones) even though the items don't exist? And why is this mix of plutonium and uranium suddenly bright purple?

**Comment by OlorinIV** [comment]
So what exactly... is the point of this thing? We have LEP, with a similar composition and an RBMK fuel. We don't need another weak RTG pellet, as Au-198 ones are incredibly cheap and powerful. We don't need another midgame self-charging battery, because if there is one in what tier should we put it in? Not to mention that its materials are crafted in such a simple manner. We do need an LEP PWR fuel, but there isn't anything yet, no formula, no recycle. And you think that making players able to make mid-tier nuclear fuels enrichment-free would be a nice idea?! 
I kindly suggest you to keep what you have thought of in your own repository, make your own build, give it test and balance. What is your point doing this how could you pull request something that is practically an empty shell?

**Comment by TheChosenIndividual** [comment]
> So what exactly... is the point of this thing? We have LEP, with a similar composition and an RBMK fuel. We don't need another weak RTG pellet, as Au-198 ones are incredibly cheap and powerful. We don't need another midgame self-charging battery, because if there is one in what tier should we put it in? Not to mention that its materials are crafted in such a simple manner. We do need an LEP PWR fuel, but there isn't anything yet, no formula, no recycle. And you think that making players able to make mid-tier nuclear fuels enrichment-free would be a nice idea?! I kindly suggest you to keep what you have thought of in your own repository, make your own build, give it test and balance. What is your point doing this how could you pull request something that is practically an empty shell?

...you know what, actually you´re right lmao, i should probably balance this, i added plate fuel as well, and somehow managed to corrupt 2 worlds doing it, i...guess i will come back in the future when this idea has evolved a little more

**Pull request closed without merging**
