### PR TITLE
Ammo variant tweaks

### PR DESCRIPTION
**Pull request by 70000hp**
**Changes:**

Adjusted all ammo variant crafting recipes to match their stock ammo crafting amounts, e.x if you've crafted a round which is made in stacks of 32, the variant will be made in stacks of 32
- This acts as a buff to several guns, making their ammo variants cheaper to craft

Chlorophyte ammo now penetrates targets, causing it to jump between mobs if their target dies
- It also has had it's recipe yield doubled, since it was not worthwhile to craft before
- While it is not as faithful to the source material, it is a significant buff to an ammo type which was nigh useless

### CODE REVIEW

**Comment by HbmMods** [comment]
Did you actually test the chlorophyte bullet penetration? Because the target isn't reset on impact and the targeting angle is now 360°, I don't see how the bullet would seek another target instead of just bouncing back and forth around the initial target.

**Comment by HbmMods** [comment]
Also wouldn't a targeting angle of 360° mean that the bullet would come out of your gun backwards if there's an entity behind you which is just a little closer to you than what you're actually trying to shoot?

**Comment by 70000hp** [comment]
> Did you actually test the chlorophyte bullet penetration? Because the target isn't reset on impact and the targeting angle is now 360°, I don't see how the bullet would seek another target instead of just bouncing back and forth around the initial target.

Oh shoot, I thought I reverted that

**Comment by 70000hp** [comment]
I'll reset the target when the entity impacts, the bullet bouncing around its initial target helped it score multiple hits on the same entity, which I thought was fairly decent damage-wise

**Comment by 70000hp** [comment]
And yes I tested the penetration extensively, it was very good at clearing out large waves of mobs, while not leaving any of them half-damaged due to the bullet jumping about the target

**Comment by 70000hp** [comment]
https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/105080577/016ee8b5-8101-4793-8ab3-7c2ab6879221

Here you go, they now dont hit stuff behind them and are much better at killing swarms

**Comment by 70000hp** [comment]
@HbmMods just incase you haven't seen, I fixed the chloro rounds issue

**Pull request merged**
