### PR TITLE
Blood

### PR DESCRIPTION
**Pull request by JameH2**
my fork was full of memes, i had to clean it up, it would be cool to have [BLOOD IS FUEL] in ntm

jet engine makes blood
villagers and players drop flesh
blood can be solidified to make flesh patties
[ULTRAKILL] trait for the chemthrower (makes people heal)
"bloodgas" fluid that makes (arguable) power

if there is any meme shit I forgot about feel free to remove
and feel free to make any balance changes.

### CODE REVIEW

**Comment by JameH2** [comment]
this sounds like a suggestion my god, its not I swear

**Comment by Antineutrino-4444** [comment]
bob is gone recently so he might not respond to things lately
so yea dont push it too hard :>

**Comment by HbmMods** [comment]
Not so much, it's rather that GitHub doesn't properly display activity from [other branches.](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/tree/m763)

**Comment by Antineutrino-4444** [comment]
o well i didnt know that
it is good to see bob still exists :D

**Comment by Vaern** [comment]
yeah, he's been having some trouble recently. here's a picture he sent us as an update on how he's doing
p3nu87dc2gr41

**Comment by burningwater202** [comment]
At least we can say he has a sole

**Comment by HbmMods** [comment]
That shoe was probably tastier than 90% of stuff I had the past few weeks. There's only that many times you can eat reheated noodles before going insane.

**Comment by JameH2** [comment]
I get the github glitch but i have no idea what they mean by “push too hard” oh well not an issue lol

**Comment by HbmMods** [comment]
juicy

**Comment by JameH2** [comment]
yaaaay!!!!

**Pull request closed without merging**
