### PR TITLE
Reworked radiation math with the reacher equipped

### PR DESCRIPTION
**Pull request by TehTemmie**
This change makes reachers reduce incoming radiation that is under 1 RAD/tick.

### CODE REVIEW

**Comment by HbmMods** [comment]
Assuming that I've interpreted the function correctly
image
wouldn't that mean that the effective dose would never exceed 0.207 RAD/t? At least that's where the function peaked on the Desmos graphing calculator.

**Comment by TehTemmie** [comment]
This is what the function is supposed to be
image
I really hope I didn't mess up my parentheses

**Comment by HbmMods** [comment]
Oops, my bad

**Comment by HbmMods** [comment]
grafik

**Pull request merged**
