### PR TITLE
Actually added Burst fire to josh now

### PR DESCRIPTION
**Pull request by 70000hp**
next time I do this, you have full permission to throw a brick at my head

### CODE REVIEW

**Comment by HbmMods** [comment]
why on god's green earth did you tie the actual burst firing into the world tick and not into the timer you specifically added to handle burst fire

**Comment by 70000hp** [comment]
> why on god's green earth did you tie the actual burst firing into the world tick and not into the timer you specifically added to handle burst fire

Because I am a pillock and decided to do this and work on glyphids at the same time

**Comment by 70000hp** [comment]
I'll fix that later

**Comment by HbmMods** [comment]
i already fixed it

**Comment by JameH2** [comment]
NO! GRAB ME GRAB ME GRAB MEEEEEEE

**Pull request merged**
