### PR TITLE
Fix #1690 (upgrading crates & mass storage)

### LINKED ISSUE #1690: Upgrading crates voids contents
It would be nice if upgrading steel crates to desh (and other similar recipes) kept the inventories intact. As of now, the inventory is reset silently

### PR DESCRIPTION
**Pull request by abel1502**
(Okay, apparently github doesn't recognize issue mentions in the title, so I'm tagging #1690 here again for the record)

### CODE REVIEW

**Comment by HbmMods** [comment]
Does the crafting handler work in NEI? Because I'm pretty sure there's no support for custom recipes in the standard NEI handler.

**Comment by abel1502** [comment]
It does, in my testing. Presumably because I inherit from `ShapedOreRecipe` and don't fundamentally change its workings either

**Comment by abel1502** [comment]
That said, I was using the unofficial NEI (`NotEnoughItems-2.6.38-GTNH.jar`). I'll test it with the original as well, just to be sure

**Comment by abel1502** [comment]
Yep, works with regular NEI too

**Comment by HbmMods** [comment]
huh i didn't think it was that easy

**Pull request merged**
