### PR TITLE
Hbm mods master

### PR DESCRIPTION
**Pull request by gqi3md**

### CODE REVIEW

**Comment by HbmMods** [comment]
what

**Comment by 70000hp** [comment]
Right so it seems this guy ran some kind of optimization program and then proceeded to randomly break features for some war server, and somehow thought merging it was a good idea

**Review by 70000hp — CHANGES_REQUESTED** [review]
You basically removed half of ntm. 
w h y

**Comment by BallOfEnergy1** [comment]
I normally try and stay formal on github but
what the fuck

**Comment by burningwater202** [comment]
45615AD0-A0AE-4174-A625-229A8B459AF1
Gtfoh

**Comment by gqi3md** [comment]
XD sorry I didnt mean to merge it here

**Comment by JameH2** [comment]
Sir, what does this even do

**Pull request closed without merging**
