### PR TITLE
this would go in issues but since it's a fork it aint gonna work

### PR DESCRIPTION
**Pull request by TheForge129**
please bring back the fluid identifier system... steam turbines won't accept dense steam

### CODE REVIEW

**Comment by HbmMods** [comment]
I hope you understand that merging Drillgon's year old master branch with this project isn't going to achieve what you want - nor that I'm the one you should be asking in the first place.

**Comment by TheForge129** [comment]
i wasnt asking you... i would've tried to pm him but that's been removed,
and i put the pull request on the fork..?
sorry, i wasn't trying to ask you... i was trying to ask him but idfk how,
since apparently the pull requests go to you

**Comment by Drillgon200** [comment]
There's literally no point in having to set tank types, and it's a pain with forge fluids which is why I didn't do that in the first place. What might actually solve your issue and be a useful feature is directional fluid pipes or machine side configurability.

**Comment by TheForge129** [comment]
yeah, i didnt mean tank types, i just mean the steam turbine wont accept
dense steam

**Comment by Drillgon200** [comment]
I tested this, and they do accept dense steam. It's just that when the second turbine finishes processing, it'll try to fill things around it and might end up filling the first turbine causing dense steam to no longer fill it. Giving them set fluid types is a band aid to a larger problem that side based access or directional pipes would fix.

**Pull request closed without merging**
