### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by sdddddf80**

### CODE REVIEW

**Comment by HbmMods** [comment]
I've already received a new version of the localization file from Bismarck#5640 which is more consistent with the one we have right now. I can't comment on the quality of either file, but is there a reason why your PR changes almost every single lang entry?

**Comment by sdddddf80** [comment]
> I've already received a new version of the localization file from Bismarck#5640 which is more consistent with the one we have right now. I can't comment on the quality of either file, but is there a reason why your PR changes almost every single lang entry?

Most of them are just differences in sentence structure, as well as some modifications to the display format (such as line breaks) to prevent text from exceeding the display range

**Comment by LSK-LW** [comment]
Here are some missing translations, check out:

armor.dash=Grants %s dashes
container.autocrafter=Automatic Crafting Table
container.craneGrabber=Conveyor Grabber
container.turretFritz=Fritz
container.turretHoward=Howard
death.attack.acidPlayer=%1$s was dissolved by %2$s.
death.attack.boil=%1$s was boiled alive by %2$s.
hadron.error_generic=Error!
hadron.error_no_charge=Error 0x01 [NC]
hadron.error_no_analysis=Error 0x02 [NA]
hadron.error_obstructed_channel=Error 0x03 [OC]
hadron.error_expected_coil=Error 0x04 [EC]
hadron.error_malformed_segment=Error 0x05 [MS]
hadron.error_analysis_too_long=Error 0x06 [ATL]
hadron.error_analysis_too_short=Error 0x07 [ATS]
hadron.error_diode_collision=Error 0x08 [DC]
hadron.error_branching_turn=Error 0x09 [BT]
item.ammo_himars_standard.name=227mm Guided Artillery Rocket Pod
item.briquette.lignite.name=Lignite Briquette
item.cape_hidden.name=Hidden Cape
item.pellet_rtg_cobalt.name=Cobalt-60 RTG Pellet
item.pellet_rtg_cobalt.desc=Not the best as an RTG, but great for gamma radiation!
item.pellet_rtg_depleted.nickel.name=Decayed Nickel RTG Pellet
item.rag.name=Cloth
item.rag_damp.name=Damp Cloth
item.sawblade.name=Sawblade
tile.concrete_smooth_stairs.name=Concrete Stairs
tile.stalagmite.asbestos.name=Asbestos Stalagmite
tool.ability.midas=Midas Touch

**Comment by Antineutrino-4444** [comment]
To bob or other English readers, these are some of the problem I spotted for the Chinese translation. Since I have no idea about how to make a PR so to all Chinese translators who know how to make a PR, please help me. THANK YOU!!!

Here are the potential problems:
5：杜纳安可以换成Duna，因为杜纳安感觉挺怪的，而且KSP应该也没翻译Duna
57：贫铀我感觉说起来更流畅一点，所以把“未浓缩的铀”改成“贫铀”应该会更好
132：Witch Taunter我感觉应该是嘲笑女巫之类的意思，虽然可能不是很准确，但是绝对不是女巫陶恩特
609：据我所知，DFC是Dark Fusion Core的意思，所以再加一个“聚变”是不是有点重复了
643：FEL是Free Electron Laser，也就是自由电子激光的意思，所以直接把FEL换成自由电子激光器就好
713～723:：对于炮台来说，只加名字应该看不懂都是啥炮塔吧，所以编辑钱的可能会更好。当然之前的翻译也有点问题，稍微细化一下应该就行
801：钻削是不是有点奇怪，改成打孔过的是不是更合适一点？
1058：反物质蛋改成野火蛋会好点吧，毕竟这是直译而且和之前的翻译更统一
1700+1702：改成火腿BF炒蛋/BF炒蛋是不是语序感觉起来合理一点
2787：没显示字体，是不是出啥问题了？
2065：为什么要改成烈火呢？野火难道不是类似于官方翻译的吗？
3360+：Desh翻译之后感觉很怪，后面的我感觉也是不要翻译Desh

剩下的似乎都没问题了，这些也是参考用的，所以如果有别的想法可以不改。

**Comment by Antineutrino-4444** [comment]
btw 哥们你有MCMOD账号吗

**Comment by HbmMods** [comment]
Had to resolve the merge conflicts manually, I hope I used the right lines.

**Pull request merged**
