### PR TITLE
Added OC compatibility to yet another block (more coming soon)

### PR DESCRIPTION
**Pull request by BallOfEnergy1**
Added OC compat to the fluid gauge to measure fluid flows.

### CODE REVIEW

**Comment by HbmMods** [comment]
Doesn't most OC code run serverside? I don't think calling I18nUtil there is a good idea

**Comment by BallOfEnergy1** [comment]
Ah, didn't think about that, I'll change it back to the way it was before.

**Comment by BallOfEnergy1** [comment]
there jesus fucking christ my IDE wants to murder me; finally got it working
also added comparator support for tanks/barrels because 70000hp kept bugging me about it

**Comment by 70000hp** [comment]
> there jesus fucking christ my IDE wants to murder me; finally got it working also added comparator support for tanks/barrels because 70000hp kept bugging me about it

:3

**Pull request merged**
