### PR TITLE
Faster conveyors

### PR DESCRIPTION
**Pull request by BallOfEnergy1**
yeah just make the higher conveyor tiers move faster, the texture files were changed due to the fact that using the `.mcmeta` file made it skip frames and just in general look crap.
(haven't tested it on a server, though it should operate mostly the same)

there 70000hp, you happy?

### CODE REVIEW

**Comment by 70000hp** [comment]
:3333333333333
very, thankie

**Comment by 70000hp** [comment]
Even though faster conveyors don't increase throughput, they reduce entity count, which is fairly important since large setups tend to lag, and just feel better to use

**Comment by BallOfEnergy1** [comment]
(and it also gives a reason for multi-lane conveyors to exist)

**Comment by HbmMods** [comment]
grafik

**Pull request closed without merging**
