### PR TITLE
The Tom Extinction

### PR DESCRIPTION
**Pull request by Troodontid**
This makes it so that Tom is truly an extinction-level event with global firestorms, darkness, and death everywhere.

### CODE REVIEW

**Comment by Joey-Destroyah** [comment]
How long would the effects last for?

**Comment by Joey-Destroyah** [comment]
Also, because your repo doesnt have an issue page, i will use this for now.

Can't build the forked mod





Log:




$ ./gradlew build
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
WARNING: You are using an unsupported version of ForgeGradle.
Please consider upgrading to ForgeGradle 4 and helping in the efforts to get old versions working on the modern toolchain.
See https://gist.github.com/TheCurle/fe7ad3ede188cbdd15c235cc75d52d4a for more info on contributing.
#################################################
         ForgeGradle 1.2.1-g1602004
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava
:compileJavaC:\Users\Joseph Goldsmith\Documents\Hbm-s-Nuclear-Tech-GIT\build\sources\java\com\hbm\config\GeneralConfig.java:76: error: unmappable character for encoding Cp1252
                                + "▒?по▒?об-528: дей▒?твовать ▒? о▒?торожно▒?тью!");
                                    ^
C:\Users\Joseph Goldsmith\Documents\Hbm-s-Nuclear-Tech-GIT\build\sources\java\com\hbm\config\GeneralConfig.java:76: error: unmappable character for encoding Cp1252
                                + "▒?по▒?об-528: дей▒?твовать ▒? о▒?торожно▒?тью!");
                                          ^
C:\Users\Joseph Goldsmith\Documents\Hbm-s-Nuclear-Tech-GIT\build\sources\java\com\hbm\config\GeneralConfig.java:76: error: unmappable character for encoding Cp1252
                                + "▒?по▒?об-528: дей▒?твовать ▒? о▒?торожно▒?тью!");
                                                            ^
C:\Users\Joseph Goldsmith\Documents\Hbm-s-Nuclear-Tech-GIT\build\sources\java\com\hbm\config\GeneralConfig.java:76: error: unmappable character for encoding Cp1252
                                + "▒?по▒?об-528: дей▒?твовать ▒? о▒?торожно▒?тью!");
                                                                             ^
C:\Users\Joseph Goldsmith\Documents\Hbm-s-Nuclear-Tech-GIT\build\sources\java\com\hbm\config\GeneralConfig.java:76: error: unmappable character for encoding Cp1252
                                + "▒?по▒?об-528: дей▒?твовать ▒? о▒?торожно▒?тью!");
                                                                                  ^
C:\Users\Joseph Goldsmith\Documents\Hbm-s-Nuclear-Tech-GIT\build\sources\java\com\hbm\config\GeneralConfig.java:76: error: unmappable character for encoding Cp1252
                                + "▒?по▒?об-528: дей▒?твовать ▒? о▒?торожно▒?тью!");
                                                                                                  ^
C:\Users\Joseph Goldsmith\Documents\Hbm-s-Nuclear-Tech-GIT\build\sources\java\com\hbm\items\food\ItemLemon.java:95: error: unmappable character for encoding Cp1252
                        list.add("у▒?луги перевода недо▒?тупны!");
                                     ^
C:\Users\Joseph Goldsmith\Documents\Hbm-s-Nuclear-Tech-GIT\build\sources\java\com\hbm\items\food\ItemLemon.java:95: error: unmappable character for encoding Cp1252
                        list.add("у▒?луги перевода недо▒?тупны!");
                                                                         ^
C:\Users\Joseph Goldsmith\Documents\Hbm-s-Nuclear-Tech-GIT\build\sources\java\com\hbm\items\special\ItemCustomLore.java:354: error: unmappable character for encoding Cp1252
                        list.add("у▒?луга перевода недо▒?тупна");
                                     ^
C:\Users\Joseph Goldsmith\Documents\Hbm-s-Nuclear-Tech-GIT\build\sources\java\com\hbm\items\special\ItemCustomLore.java:354: error: unmappable character for encoding Cp1252
                        list.add("у▒?луга перевода недо▒?тупна");
                                                                         ^
C:\Users\Joseph Goldsmith\Documents\Hbm-s-Nuclear-Tech-GIT\build\sources\java\com\hbm\items\special\ItemDigamma.java:41: error: unmappable character for encoding Cp1252
                list.add(EnumChatFormatting.GOLD + I18nUtil.resolveKey("trait.hlParticle", "1.67*10³▒?▒a"));
                                                                                                      ^

**Comment by Troodontid** [comment]
The firestorm lasts for a full MC day, and the dust takes 600 days to clear out of the atmosphere. As for those build errors, that’s basically gradle not liking specific unicode characters.

**Comment by Joey-Destroyah** [comment]
I love the idea of an actual ELE meteor, like those dinos 66 million years ago.

**Comment by Troodontid** [comment]
That’s actually what this is modeled on.

**Comment by Joey-Destroyah** [comment]
During startup, the build crashes.


The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.ExceptionInInitializerError
Exit Code: -1
[crash-2021-10-22_20.48.31-client.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/7401980/crash-2021-10-22_20.48.31-client.txt)

**Comment by Joey-Destroyah** [comment]
> The firestorm lasts for a full MC day, and the dust takes 600 days to clear out of the atmosphere. As for those build errors, that’s basically gradle not liking specific unicode characters.

What would happen during the time that the dust clogs up the atmosphere?

**Comment by Troodontid** [comment]
The crash is because you're somehow missing a model file (turret_chekhov.obj). As for the dust, it blocks out the sun, resulting in the death of any plant life that isn't illuminated by artificial lighting. As time passes, the dust slowly settles, and light levels increase until they reach their pre-impact levels.

**Comment by Joey-Destroyah** [comment]
I downloaded the files using git bash

**Comment by HbmMods** [comment]
Merged locally.

**Pull request closed without merging**
