### PR TITLE
The Almighty toorb

### PR DESCRIPTION
**Pull request by Pvndols**
i sure do hope i'm doing shit right
- added the Combined Cycle Gas Turbine

### CODE REVIEW

**Comment by HbmMods** [comment]
Are there any changes/additions other than the turbine itself? The PR branch also contains changes merged from the main branch which makes auto merging impossible and finding the exact changes very hard (2,100+ changed files make the diff viewer lag to hell).

**Comment by Pvndols** [comment]
iirc, i made the fracker(and maybe all the oil wells? idk) store its energy to NBT, a long time ago, idk if that could be the issue

**Comment by HbmMods** [comment]
Could you send me a non-triangulated OBJ of the gas turbine? There's some normal/lighting stuff I want to fix.

**Comment by Pvndols** [comment]
imma send it to u on discord, github doesn't let me upload it. Fusion360 exports an obj that's already made of triangles, and i can't find a way to make it not happen

**Comment by HbmMods** [comment]
Eh I'll just undo the triangulation myself then

**Comment by HbmMods** [comment]
Added some sharp cuts where the pipes (cylinders?) meet the main disk thing because it looked weird otherwise, as well as a few other parts that should be sharp.

**Comment by HbmMods** [comment]
Merged locally.

**Pull request closed without merging**
