### PR TITLE
Updated ru_RU.lang

### PR DESCRIPTION
**Pull request by Doctor17-git**
finally
.lang keys for items descriptions

### CODE REVIEW

**Comment by sendhelppls213** [comment]
I can see where this is going.

**Comment by Doctor17-git** [comment]
yeah so let's just leave it at that

**Comment by sendhelppls213** [comment]
eeyup, sounds about right.

**Comment by Nos74** [comment]
bepis

**Comment by HbmMods** [comment]
orbducc2

**Comment by HbmMods** [comment]
vision

**Pull request merged**
