### PR TITLE
Fix quotes in resource file

### PR DESCRIPTION
**Pull request by Majora320**

### CODE REVIEW

**Comment by 70000hp** [comment]
What
Why?

**Comment by 9Valjew** [comment]
huh?

**Comment by JameH2** [comment]
Wdym fixing? Those slashes are escape sequences

**Comment by Majora320** [comment]
Open Minecraft and look at the descriptions of the items I changed, the backslashes get rendered verbatim.

**Comment by MellowArpeggiation** [comment]
He's right, the backslashes aren't required in `.lang` files, and are rendered as regular text. It's likely that the text was copied from code (where the escape sequence _is_ required) when migrated to the localized files with the backslashes still intact.

**Comment by Vaern** [comment]
this is why you localize from the start

**Pull request merged**
