### PR TITLE
Fixed gamebreaking bug with the leviathan turbine

### PR DESCRIPTION
**Pull request by 9Valjew**
I should get a bobble for this fr

### CODE REVIEW

**Comment by JameH2** [comment]
The hell did you change

**Comment by 9Valjew** [comment]
> The hell did you change

tumbine

**Comment by gmhs022** [comment]
Oh my god I see it, there was a 1-pixel error on the upside-down warning sign on the texture

**Comment by HbmMods** [comment]
regrettably i have to inform you that we can't fix this bug because it would cause severe compatibility issues with older worlds

**Comment by 9Valjew** [comment]
> regrettably i have to inform you that we can't fix this bug because it would cause severe compatibility issues with older worlds

Such a shame, I guess the mod is now in shambles

**Pull request closed without merging**
