### PR TITLE
Upstream Space Shit

### PR DESCRIPTION
**Pull request by MellowArpeggiation**
with bonus EndlessIDs compat (entirely soft-dep):
* Endless IDs compatibility, runs normally when not installed
* Bob's new basalt textures + basalt ores
* Fixes for middle clicking/NEI overlay/WAILA overlay on basalt ores and stalactites/mites/shites
* Horizontal scaffolding
* Fix GL state leak on fluid tanks

Bob if you want the dummyable changes that allow for placing on walls/ceilings and make the machines semi-solid to the placing player until they leave the hitbox lemme know and I'll add it to this PR

### CODE REVIEW

**Comment by MellowArpeggiation** [comment]
fucking hell the mere presence of a `compileOnly` dep that requires mixins fucks up ALL the reobfuscation making _only_ the build fail and nothing else god fucking damn it.

**Comment by MellowArpeggiation** [comment]
okay fixed, make sure to run `clean` and `setupDecompWorkspace`, should never be an issue for soft-deps that happen to use mixins ever again.

**Comment by HbmMods** [comment]
What's happening in ModBlocks?

**Comment by MellowArpeggiation** [comment]
huh, that’s wack, it’s just a change for basalt to BlockPillar and a new function at the end, no idea why git cherry pick did that

**Pull request merged**
