### PR TITLE
my life is pain, why did I decide to do this

### PR DESCRIPTION
**Pull request by ShimmeringBlaze**

### CODE REVIEW

**Review by UFFR — CHANGES_REQUESTED** [review]
Do you have time to talk about our lord and savior, the ternary operator?

```java
return (MainRegistry.polaroidID == 11 ? blaze2 : shimmeringblaze);
````

**Comment by ShimmeringBlaze** [comment]
I really just did the same thing as the other times the polaroidID is referenced, so it matches

**Comment by ShimmeringBlaze** [comment]
Finally figured it out

**Comment by HbmMods** [comment]
Praise be!

**Comment by ShimmeringBlaze** [comment]
Yeah, I think I did that right

**Pull request merged**
