### PR TITLE
Updated OpenComputers compatibility + slight change to concrete blast res

### PR DESCRIPTION
**Pull request by BallOfEnergy1**
Modified concrete bricks and rebar reinforced concrete blast resistance to be more reasonable based on their recipes.

### CODE REVIEW

**Comment by BallOfEnergy1** [comment]
PR now contains a large OC compatibility change deprecating a moderate number of functions and replacing them with more efficient functions.

**Comment by PewPewCricket** [comment]
I can't wait until this is in the mod :)

**Comment by BallOfEnergy1** [comment]
hold on i fucked something up
man
why :despair:

**Comment by BallOfEnergy1** [comment]
alright it should be fixed; github merged a PR for me, giving me a mini heart attack
ready for merge

woo!

**Comment by HbmMods** [comment]
Is there a reason you removed OC integration from the pipe gauge? Also the code in the RBMK steam column is probably unnecessary since changing the type already resets the fill state.

**Comment by BallOfEnergy1** [comment]
The original reason I removed OC compatibility from the pipe gauge was someone experienced an error when attempting to load the mod, though it seems like it's resolved so I'll add it back in.
I didn't see the code where it cleared the fill on type changed, as that's why I added it in, I'll change it back now.

**Comment by BallOfEnergy1** [comment]
all done and fixed

**Pull request merged**
