### PR TITLE
Something About Pollution

### PR DESCRIPTION
**Pull request by sdddddf80**
SOOT now cause black lung. Add effectiveness in releasing toxic fluids for Flare Stack and damaged fluid tanks.

### CODE REVIEW

**Comment by ghost** [comment]
awesome

**Comment by BillyGG2000** [comment]
you should make a missile launch console for remote launching and convenience

**Comment by ghost** [comment]
maybe more like Pollution of the Realms but invisible but if you have pollution glasses you can see the pollution?

**Comment by BallOfEnergy1** [comment]
> you should make a missile launch console for remote launching and convenience

OC integration:

**Pull request closed without merging**
