### PR TITLE
Fixup build.gradle, fixes #63

### LINKED ISSUE #63: git won't compile
Okay, so I was looking to this "HBM's Nuclear Tech Mod" to be able to add compat for things like GT6 and HEXCraft, however I am unable to find a maven for it and the git for it at https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT.git (not able to find any other) is not compileable to be able to build a proper dependency for it, so I'm not seeing that this will ever be done until either it gets a proper maven repo or it gets a properly set up git project (look at GT6 or HEXCraft git repo's as example, they are a trivial `git clone ...` and `./gradlew build` in their directories and it all 'just works').

_Originally posted by @OvermindDL1 in https://github.com/CelesTek-Team/HexCraft/issues/22#issuecomment-647624023_

For note, if help is wanted to be able to get the git repo for the "HBM's Nuclear Tech Mod" into a proper compileable state then feel free to contact me on IRC at espernet, I'm OvermindDL1 there.

_Originally posted by @OvermindDL1 in https://github.com/CelesTek-Team/HexCraft/issues/22#issuecomment-647624917_

### PR DESCRIPTION
**Pull request by OvermindDL1**
This uses the GT maven instead of the broken forge maven, sets defaults based on what is seen in code and on git for version, and should be a simple clone and build.

Testing a build here is successful:
```zsh
➜ ./gradlew setupCIWorkspace assemble
:downloadClient SKIPPED
:downloadServer SKIPPED
:getVersionJson
:extractUserDev
:mergeJars SKIPPED
:applyBinPatches SKIPPED
:downloadMcpTools SKIPPED
:extractMcpData
:genSrgs SKIPPED
:deobfBinJar SKIPPED
:setupCIWorkspace UP-TO-DATE
:compileApiJava NO-SOURCE
:processApiResources NO-SOURCE
:apiClasses UP-TO-DATE
:sourceMainJava
:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:processResources
:classes
:devJar
:jar
:reobf
:sourceJar
:assemble

BUILD SUCCESSFUL

Total time: 27.394 secs

➜ ls build/libs 
hbm-1.0.27-dev.jar  hbm-1.0.27.jar  hbm-1.0.27-sources.jar

```

I have not tested the mod itself as I'm at work without a GUI, so I cannot assert that the mcmod.info and assets and such are correct, but it 'looks' correct, please test.

Also, if you want a maven server to host it then I can supply it if you so wish, otherwise this is the minimum necessary for it to be useful to other projects to be used as a dependency.

### CODE REVIEW

**Comment by OvermindDL1** [comment]
You may see fit to adjust the `archivesBaseName` if you want it to be something else, it should be the name of the mod in standard java identifier format (so `[a-z0-9_]+` format, a-z, 0-9, and underscores, no spaces, no capitalization, etc...).

Also, you can add the curseforge plugin now as well to automate uploading new versions to curseforge as well.  I'm no curseforge fan at all so I'm afraid I can't help with that part, but I hear it's simple enough as well.  Just add the curseforge section to the bottom of your build.gradle after importing its plugin.

**Comment by HbmMods** [comment]
I see you updated the required versions of the codechicken and NEI libraries, but where exactly can I get those libraries? I saw you added links to your HexCraft fork, but the forge site no longer hosts the codechicken files, which means half of the links are dead.

**Comment by OvermindDL1** [comment]
> I see you updated the required versions of the codechicken and NEI libraries

Yes, the bug fixes are very important.

> but where exactly can I get those libraries

They are acquired via maven automatically.

> I saw you added links to your HexCraft fork

Huh?  Where at?  o.O

> but the forge site no longer hosts the codechicken files

The forge site isn't being used at all in the file, did I leave it in somewhere?

> which means half of the links are dead

Which links?

**Comment by OvermindDL1** [comment]
Have you not tried this PR yet?  It should be a simple git clone and compile, as shown in the commands above.

**Comment by HbmMods** [comment]
> Huh? Where at? o.O

At least your fork has links to all required libs and the original repo doesn't, I assumed you might have updated the readme

> The forge site isn't being used at all in the file, did I leave it in somewhere?

No, but that's both where I got my version of the libraries and where the HexCraft readme leads to, I was just worried because what appears to be the "official" host no longer had those files

> They are acquired via maven automatically.

That might have been what confused me, I wasn't aware maven could do that.

**Comment by OvermindDL1** [comment]
> At least your fork has links to all required libs and the original repo doesn't, I assumed you might have updated the readme

I try not to touch other files than what what I'm specifically building, minimal git changes.  :-)

> No, but that's both where I got my version of the libraries and where the HexCraft readme leads to, I was just worried because what appears to be the "official" host no longer had those files

Do remember that I was the original host of the forge project years ago.  When I left the forge project (due to issues in design decisions that they kept messing up, as you see with the current status of their servers) I kept running what was needed for 1.7.10 development and keeping it updated it over time.  So it may be on a different URL now but my server 'is' the original official forge maven host (though most of it is disabled as I haven't had any requests to bring up other parts of it, but I can spool up any part of it again in seconds).  :-)

> That might have been what confused me, I wasn't aware maven could do that.

Ah!  Yeah that's the whole purpose of maven.  Maven is nothing but a dependency management service, it's a whole protocol and API about how to acquire and manage dependencies (gradle uses maven as its dependency management resolver).  :-)

If you need any other 1.7.10 mods via maven for developing using them, I probably already either have it available (ask me for the maven information, ping me here on Github or on IRC or so) or can host if you can show me their compileable git repo or something equivalent.  I have quite literally hundreds available as it stands currently though so you'd be surprised at what is already available.  ^.^

**Comment by HbmMods** [comment]
Alright, the project build successfully, but I'm not able to start it in eclipse since the codechicken libraries no longer exist (of course they don't), and I can't seem to find them in the library folder that the build process created. It did download 60 MBs worth of *something* but it doesn't appear to have anything related to NEI in it.

> I kept running what was needed for 1.7.10 development and keeping it updated it over time. So it may be on a different URL now but my server 'is' the original official forge maven host

Wow, it's great to hear that, despite being almost 6 years old now, this version still gets some love.

**Comment by OvermindDL1** [comment]
> Alright, the project build successfully, but I'm not able to start it in eclipse since the codechicken libraries no longer exist (of course they don't), and I can't seem to find them in the library folder that the build process created. It did download 60 MBs worth of something but it doesn't appear to have anything related to NEI in it.

They were downloaded into the gradle cache.  Eclipse is notoriously bad at build system handling (I prefer IntelliJ) but it should work without issue if eclipse opens it as a gradle project, not as it's own custom internal broken format.

If your version of eclipse is old enough that it doesn't handle gradle well (intellij handles gradle perfectly, it's built-in supported) then I can add eclipse handling to your gradle file to generate an eclipse project that will work.  But you 'should' be able to just open the project in eclipse 'as' a gradle project.  To launch the game, say for debugging or testing or so from inside the IDE, just have it run the `runClient` gradle task.  To build just have it run the `assemble` gradle task.

If you don't want to run the debugger in eclipse you can always just run `./gradlew runClient` directly from the commandline too.  ^.^

> Wow, it's great to hear that, despite being almost 6 years old now, this version still gets some love.

You'd be surprised how many mods are still having regular active development for 1.7.10.  1.8 and above had such overhauls and inefficiencies that most don't want to migrate, so 1.7.10 has become a fairly stable version for them to work on.

**Comment by OvermindDL1** [comment]
If you want assistance in real-time I'm available on a few different messaging services as well if you have preference.

**Comment by HbmMods** [comment]
> If your version of eclipse is old enough that it doesn't handle gradle well

I assume that is the case, I'm still using Eclipse Neon.1, mainly because all newer versions I've tried are bugged in some way. If you could make a more Eclipse-friendly version, that would be awesome!

> To launch the game, say for debugging or testing or so from inside the IDE, just have it run the `runClient` gradle task.

Color me surprised, I never even thought about starting the game from the terminal!

> You'd be surprised how many mods are still having regular active development for 1.7.10.

Color me even more surprised, with the exception of two larger technic mods and some specialized modpacks, I haven't really heard about anyone still working with 1.7! Then again, I haven't interacted with the community in about 2 years, mainly because of the constant "1.7.10 dead lol" talks.

**Comment by OvermindDL1** [comment]
> I assume that is the case, I'm still using Eclipse Neon.1, mainly because all newer versions I've tried are bugged in some way. If you could make a more Eclipse-friendly version, that would be awesome!

Ah, very possible, let me try to get some time soon and I'll build the eclipse workspace generator in it.  I won't be able to test it as I don't have eclipse (I really do recommend trying [IntelliJ IDEA Community Edition](https://www.jetbrains.com/idea/download/), it's free and is a whole lot more capable as a Java IDE than Eclipse is, with a significantly larger plugin community), but it works for GT6 (which I originally built it for), lol.  ^.^

> Color me surprised, I never even thought about starting the game from the terminal!

Yep yep, gradle is fully CLI driven, even Eclipse/IntelliJ is just running the same commands.  Like run `./gradlew tasks` to get a list of the public tasks you can run.  If you want to `runClient` with, say, more memory, you don't need to specify that on the command every time, you can make it default by adding, say, this into your build.gradle file:
```gradle
runClient {
	jvmArgs "-Xmx4096m", "-Xms1024m"
}

runServer {
	jvmArgs "-Xmx4096m", "-Xms1024m"
}
```
Gradle handles it all, including a background build server to make rebuilds even faster.

> Color me even more surprised, with the exception of two larger technic mods and some specialized modpacks, I haven't really heard about anyone still working with 1.7! Then again, I haven't interacted with the community in about 2 years, mainly because of the constant "1.7.10 dead lol" talks.

Oh yeah there is a *lot* more than that.  ^.^
And sure 1.7.10 is dead, but the modding community for it is very much alive (and a lot more pleasant to deal with than later ones as these tend to be people that just care about happily modding).  :-)

A few of the modders mostly congregate in #gt-dev on EsperNet IRC if you want to hop on, it's very much not just GT6 talk.  :-)

**Comment by GregoriusT** [comment]
> Color me even more surprised, with the exception of two larger technic mods and some specialized modpacks, I haven't really heard about anyone still working with 1.7!

Hey, I am technically still working on Bugfixes and some rare Compat Jobs. XD

> A few of the modders mostly congregate in #gt-dev on EsperNet IRC if you want to hop on, it's very much not just GT6 talk. :-)

Yeah plenty of nice and weird people around there, I dont know why I attract so many of those, maybe because I am one myself. XD

**Pull request merged**
